import os

session_path = os.path.join(os.path.dirname(__file__), 'src', 'Session.jsx')

new_content = (
    "import { useState, useMemo } from 'react'\n"
    "\n"
    "const EMOTIONS = ['calm', 'focused', 'anxious', 'frustrated', 'overconfident', 'fearful', 'revenge']\n"
    "const EMO_COLORS = { calm: '#16a34a', focused: '#2563eb', anxious: '#d97706', frustrated: '#ea580c', overconfident: '#db2777', fearful: '#7c3aed', revenge: '#ef4444' }\n"
    "\n"
    "const CHECKLIST = [\n"
    "  'I have reviewed the higher timeframe bias',\n"
    "  'I know my max loss for today',\n"
    "  'I am not trading to recover yesterday\\'s losses',\n"
    "  'My stop losses are defined before I enter',\n"
    "  'I am not sizing up to make back money faster',\n"
    "  'I am in a calm, focused headspace',\n"
    "  'I have a valid setup - not just a feeling',\n"
    "]\n"
    "\n"
    "const CARD = { background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10, padding: 20, marginBottom: 16, boxShadow: 'var(--shadow)' }\n"
    "const LABEL = { fontSize: 10, color: 'var(--text3)', letterSpacing: '.08em', marginBottom: 14 }\n"
    "\n"
    "export default function Session({ sessions, trades, onSave }) {\n"
    "  const today = new Date().toISOString().slice(0, 10)\n"
    "  const existing = sessions.find(s => s.date === today) || {}\n"
    "\n"
    "  const [preEmo, setPreEmo] = useState(existing.pre_emotion || '')\n"
    "  const [preNotes, setPreNotes] = useState(existing.pre_notes || '')\n"
    "  const [postEmo, setPostEmo] = useState(existing.post_emotion || '')\n"
    "  const [postNotes, setPostNotes] = useState(existing.post_notes || '')\n"
    "  const [followedPlan, setFollowedPlan] = useState(existing.followed_plan || '')\n"
    "  const [grade, setGrade] = useState(existing.overall_grade || '')\n"
    "  const [checks, setChecks] = useState({})\n"
    "  const [saved, setSaved] = useState(false)\n"
    "  const [saving, setSaving] = useState(false)\n"
    "\n"
    "  const todayTrades = useMemo(() => trades.filter(t => t.openTime?.slice(0, 10) === today), [trades, today])\n"
    "  const todayPnl = todayTrades.reduce((s, t) => s + t.profit, 0)\n"
    "  const allChecked = CHECKLIST.every((_, i) => checks[i])\n"
    "\n"
    "  function toggleCheck(i) { setChecks(p => ({ ...p, [i]: !p[i] })) }\n"
    "\n"
    "  async function handleSave() {\n"
    "    setSaving(true)\n"
    "    await onSave({ date: today, preEmotion: preEmo, preNotes, postEmotion: postEmo, postNotes, followedPlan, overallGrade: grade })\n"
    "    setSaved(true)\n"
    "    setSaving(false)\n"
    "    setTimeout(() => setSaved(false), 2000)\n"
    "  }\n"
    "\n"
    "  const pill = (val, current, setter, color) => (\n"
    "    <button key={val} onClick={() => setter(val)} style={{\n"
    "      padding: '5px 12px', borderRadius: 100, fontSize: 11, fontFamily: 'var(--font-mono)',\n"
    "      background: current === val ? color + '18' : 'var(--bg3)',\n"
    "      border: `1px solid ${current === val ? color : 'var(--border2)'}`,\n"
    "      color: current === val ? color : 'var(--text2)', cursor: 'pointer', transition: 'all .12s',\n"
    "      fontWeight: current === val ? 500 : 400,\n"
    "    }}>{val}</button>\n"
    "  )\n"
    "\n"
    "  return (\n"
    "    <div style={{ padding: '24px 20px', maxWidth: 720, margin: '0 auto' }}>\n"
    "      <div style={{ marginBottom: 28 }}>\n"
    "        <div style={{ fontFamily: 'var(--font-display)', fontSize: 26, fontWeight: 800, marginBottom: 4 }}>Session journal</div>\n"
    "        <div style={{ color: 'var(--text3)', fontSize: 12 }}>\n"
    "          {today} - {todayTrades.length} trades today\n"
    "          {todayTrades.length > 0 && <span style={{ color: todayPnl >= 0 ? 'var(--green)' : 'var(--red)', fontWeight: 500, marginLeft: 6 }}>{todayPnl >= 0 ? '+' : ''}{todayPnl.toFixed(2)}</span>}\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div style={CARD}>\n"
    "        <div style={LABEL}>PRE-SESSION CHECKLIST</div>\n"
    "        {CHECKLIST.map((item, i) => (\n"
    "          <div key={i} onClick={() => toggleCheck(i)} style={{ display: 'flex', gap: 10, alignItems: 'flex-start', padding: '8px 0', borderBottom: '1px solid var(--border)', cursor: 'pointer' }}>\n"
    "            <div style={{\n"
    "              width: 16, height: 16, borderRadius: 4, flexShrink: 0, marginTop: 1,\n"
    "              border: `1.5px solid ${checks[i] ? 'var(--accent)' : 'var(--border2)'}`,\n"
    "              background: checks[i] ? 'var(--accent-bg)' : 'transparent',\n"
    "              display: 'flex', alignItems: 'center', justifyContent: 'center',\n"
    "            }}>\n"
    "              {checks[i] && <div style={{ width: 8, height: 8, borderRadius: 2, background: 'var(--accent)' }} />}\n"
    "            </div>\n"
    "            <span style={{ fontSize: 12, color: checks[i] ? 'var(--text)' : 'var(--text2)', lineHeight: 1.5 }}>{item}</span>\n"
    "          </div>\n"
    "        ))}\n"
    "        {!allChecked && (\n"
    "          <div style={{ marginTop: 14, padding: '10px 14px', background: 'var(--amber-bg)', border: '1px solid #fde68a', borderRadius: 6, fontSize: 12, color: 'var(--amber)' }}>\n"
    "            Complete all checks before trading. If you cannot tick one honestly, consider waiting.\n"
    "          </div>\n"
    "        )}\n"
    "        {allChecked && (\n"
    "          <div style={{ marginTop: 14, padding: '10px 14px', background: 'var(--green-bg)', border: '1px solid var(--green-border)', borderRadius: 6, fontSize: 12, color: 'var(--green)' }}>\n"
    "            All clear. You are ready to trade.\n"
    "          </div>\n"
    "        )}\n"
    "      </div>\n"
    "\n"
    "      <div style={CARD}>\n"
    "        <div style={LABEL}>HOW DO YOU FEEL BEFORE TRADING?</div>\n"
    "        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 14 }}>\n"
    "          {EMOTIONS.map(e => pill(e, preEmo, setPreEmo, EMO_COLORS[e]))}\n"
    "        </div>\n"
    "        <textarea\n"
    "          value={preNotes}\n"
    "          onChange={e => setPreNotes(e.target.value)}\n"
    "          placeholder=\"What's your mindset going into today? Any concerns?\"\n"
    "          style={{ fontSize: 12, width: '100%', resize: 'vertical', minHeight: 72 }}\n"
    "        />\n"
    "      </div>\n"
    "\n"
    "      {todayTrades.length > 0 && (\n"
    "        <div style={CARD}>\n"
    "          <div style={LABEL}>POST-SESSION DEBRIEF</div>\n"
    "\n"
    "          <div style={{ fontSize: 11, color: 'var(--text2)', marginBottom: 8 }}>How are you feeling after the session?</div>\n"
    "          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 16 }}>\n"
    "            {EMOTIONS.map(e => pill(e, postEmo, setPostEmo, EMO_COLORS[e]))}\n"
    "          </div>\n"
    "\n"
    "          <div style={{ fontSize: 11, color: 'var(--text2)', marginBottom: 8 }}>Did you follow your trading plan?</div>\n"
    "          <div style={{ display: 'flex', gap: 6, marginBottom: 16 }}>\n"
    "            {[['yes', '#16a34a'], ['partially', '#d97706'], ['no', '#ef4444']].map(([v, c]) => pill(v, followedPlan, setFollowedPlan, c))}\n"
    "          </div>\n"
    "\n"
    "          <div style={{ fontSize: 11, color: 'var(--text2)', marginBottom: 8 }}>Overall session grade</div>\n"
    "          <div style={{ display: 'flex', gap: 6, marginBottom: 16 }}>\n"
    "            {[['A', '#16a34a'], ['B', '#2563eb'], ['C', '#d97706'], ['D', '#ef4444']].map(([v, c]) => pill(v, grade, setGrade, c))}\n"
    "          </div>\n"
    "\n"
    "          <textarea\n"
    "            value={postNotes}\n"
    "            onChange={e => setPostNotes(e.target.value)}\n"
    "            placeholder=\"What happened today? What did you do well? What would you change?\"\n"
    "            style={{ fontSize: 12, width: '100%', resize: 'vertical', minHeight: 100 }}\n"
    "          />\n"
    "        </div>\n"
    "      )}\n"
    "\n"
    "      <button onClick={handleSave} disabled={saving} style={{\n"
    "        width: '100%', padding: 12, borderRadius: 'var(--r)',\n"
    "        background: 'var(--accent)', color: '#fff',\n"
    "        fontFamily: 'var(--font-mono)', fontWeight: 500, fontSize: 13, border: 'none', cursor: 'pointer',\n"
    "        opacity: saving ? 0.7 : 1,\n"
    "      }}>\n"
    "        {saving ? 'saving...' : saved ? 'saved' : 'save session'}\n"
    "      </button>\n"
    "\n"
    "      {sessions.length > 0 && (\n"
    "        <div style={{ marginTop: 28 }}>\n"
    "          <div style={{ fontSize: 10, color: 'var(--text3)', letterSpacing: '.08em', marginBottom: 12 }}>PAST SESSIONS</div>\n"
    "          {sessions.slice(0, 7).map(s => (\n"
    "            <div key={s.date} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '10px 0', borderBottom: '1px solid var(--border)', flexWrap: 'wrap' }}>\n"
    "              <span style={{ fontSize: 11, color: 'var(--text3)', width: 90, flexShrink: 0 }}>{s.date}</span>\n"
    "              {s.pre_emotion && (\n"
    "                <span style={{ fontSize: 11, color: EMO_COLORS[s.pre_emotion] || 'var(--text3)', background: (EMO_COLORS[s.pre_emotion] || '#888') + '15', padding: '2px 8px', borderRadius: 100 }}>\n"
    "                  {s.pre_emotion}\n"
    "                </span>\n"
    "              )}\n"
    "              {s.post_emotion && (\n"
    "                <>\n"
    "                  <span style={{ fontSize: 10, color: 'var(--text3)' }}>to</span>\n"
    "                  <span style={{ fontSize: 11, color: EMO_COLORS[s.post_emotion] || 'var(--text3)', background: (EMO_COLORS[s.post_emotion] || '#888') + '15', padding: '2px 8px', borderRadius: 100 }}>\n"
    "                    {s.post_emotion}\n"
    "                  </span>\n"
    "                </>\n"
    "              )}\n"
    "              <div style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center' }}>\n"
    "                {s.followed_plan && (\n"
    "                  <span style={{ fontSize: 10, color: s.followed_plan === 'yes' ? 'var(--green)' : s.followed_plan === 'no' ? 'var(--red)' : 'var(--amber)' }}>\n"
    "                    plan: {s.followed_plan}\n"
    "                  </span>\n"
    "                )}\n"
    "                {s.overall_grade && (\n"
    "                  <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--accent)', background: 'var(--accent-bg)', padding: '1px 8px', borderRadius: 6 }}>{s.overall_grade}</span>\n"
    "                )}\n"
    "              </div>\n"
    "            </div>\n"
    "          ))}\n"
    "        </div>\n"
    "      )}\n"
    "    </div>\n"
    "  )\n"
    "}\n"
)

with open(session_path, 'w', newline='') as f:
    f.write(new_content)

check = open(session_path).read()
print('OK:', '#16a34a' in check and 'const CARD' in check)
print('No dark:', '#141414' not in check)
print('EMO line:', check.splitlines()[3][:70])
